apiVersion: v1
data:
    password: ENC[AES256_GCM,data:6NFpPloODMvRGpFTv5T3Xpxaiiw=,iv:us6PrUTXnd2r0njk7r4dvDyAoR0CzW85p3ivFxYO218=,tag:DPy5CzTNqT+QuvsmtNW4WQ==,type:str]
    username: ENC[AES256_GCM,data:uXOGBkBGLVc=,iv:Y9sOAokYIZQIxe77Viu9cFO3La/ev4rX/TwJvkD1MiM=,tag:t8cnNYoXrrX8OsuIhwHXsA==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2026-06-12T13:00:10Z"
    name: bigip-login
    namespace: kube-system
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMa0xBODFEUVluaUsxQWYx
            NkxDSU0ya1FPeXgwTnY4N1ZhdUhhZktuZ3dFCmFneDhQUnU2dU5lUjUveGR4RFJX
            Y2U4ZkVUYWVVdTJ5dWF1ay82RFVzK1UKLS0tIEphQTNuWk91VTQxWlpoS0x3T1JE
            QkNETEtPOTZORWRtZ2VYelo3emc5dmcKUawiW4q1eay1bqBlAbQNL8ULH0aiMU6E
            CGIhb9asABUFo+dG/FbuKVA+HcmNJI3/J1Z5UlR7S6vEne+QaiWWFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ujlph0ptql3ys5ru2pc2kp4247845phntqprfllp4nmhe0wv9gvqjgw30q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T21:57:36Z"
    mac: ENC[AES256_GCM,data:Nx/rXFNciU9kdoIHu0t6n8aPKKj06DdAdDLH9ADi08KlA4Idtw2uvBAkMk0L2FWVD1e4SANPn7VdAO8I4SKlQbSHLI+qKWyRPUy2/VSHsg0M5W4DBrbEDcKpWpMYG955RlLgNhpz2iDBzEDDSXPZC9FpxhKfNsk8h4lPyhrPKgw=,iv:OhNV+tVWfz81fS/MBm3UkvpUixSM2CIXHq6B5vUfeTI=,tag:8O0IO1S/Tr7znmW7JmQR0w==,type:str]
    version: 3.13.1
