apiVersion: ENC[AES256_GCM,data:l4w=,iv:46Sj86xKB9c9yLd18y903PLxT7CVQ4WPyQ9YjfOqjQM=,tag:b4m4+3WLQwX1ApUpESlkBA==,type:str]
data:
    password: ENC[AES256_GCM,data:wJIVwzFqqkjIG1KaFs8X7/eTGCQ=,iv:EicIr3G2trhHJSFgNXWS02RsPloPlsfFOub6/AGa/7w=,tag:h7KRktuoNyXL1YLoY5+vOQ==,type:str]
    username: ENC[AES256_GCM,data:FteV/YspX8M=,iv:DWn/rqWvIHLB+p3Noemfvc9cdLXrK1pTHZwy9HUYoO0=,tag:/Ll+Edu30lzdywNtuvVOrA==,type:str]
kind: ENC[AES256_GCM,data:wYRzfbe5,iv:06fWckbkP9y5AWA0rkqyjgFqHDfn0F/M5tvGVHZUYnE=,tag:lgbBiOjTP/daziqdMh9Yxw==,type:str]
metadata:
    creationTimestamp: ENC[AES256_GCM,data:1oBssmwIbLfRqyU+iuSIbCwis4Y=,iv:OqYJT18t8h6O9Vl6TvYt/FDmHtR2y8uP29ULaYs194A=,tag:IRNzO+SDpSy4zjBmymwcUQ==,type:str]
    name: ENC[AES256_GCM,data:7Efa/3m/W/Gk/uM=,iv:JhhvzIYRxyr4Zrae4PRRLd/3U3XDr3ZQdObMzyBWW6k=,tag:RbU0O6E6RbttsUgI7+lx0A==,type:str]
    namespace: ENC[AES256_GCM,data:ZtQiqiI1WVPrBHw=,iv:1g3swW8MjIlm8hXcUtWQAAua54+aC58mtTBcL+pUiYY=,tag:oLViTM704/OSBuh1RVzzqA==,type:str]
    resourceVersion: ENC[AES256_GCM,data:Lc60F4xK,iv:GfIVlpmcH9W/ZyCzaUv1lWP37VG4/98pbYpu0h7Ges8=,tag:NRJcJHDx8o/yeuJJLqedhA==,type:str]
    uid: ENC[AES256_GCM,data:wDn2HhEDrzxn5LLa9p1oDx6Oc5SJYRaHeBMC8vUz6UVg855B,iv:cSYAp+7KYlywNMHDdzcdz9xaz46lTNta6uRkQN3Q6Ho=,tag:pf/p0OEZAyneXOe6OD6y2g==,type:str]
type: ENC[AES256_GCM,data:xLKrr7iN,iv:jkPvL1SQpvluD4kIKR3oLUYP0Qv2qQ3h8H5BT9eGQ/g=,tag:IGyTLSX4UuFHbHQkRH1xwA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOTZTVjd2T2c1VFAxc01y
            eVNPK0tnZi9rYU5ZU1M0Zk9mYUdwMTVHdkVBCitjN04wL0FnMDNxQ1FUcUdhOHZx
            bm9Mdlo1YmJVWiszK0tSdUQyQUpaMEkKLS0tIEJBMTVpbWhBTUpqUHQveS9zczly
            NFFTUTVKNzFXeXorOHJocERtTzcxNFUKccjEiCLXO7EuDDiR/m+8CQ3z6uidSIVi
            v3KlKfplYHD7logsjDamD4At9lJEFMBbA+c9wWPTna7XPR5p4aLO9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ujlph0ptql3ys5ru2pc2kp4247845phntqprfllp4nmhe0wv9gvqjgw30q
    lastmodified: "2026-06-15T21:21:41Z"
    mac: ENC[AES256_GCM,data:VhHciYf1Ru3BxrO3pnurCrQF/W8lrxTxbVeQK5VK0BJHELzl6DSKRRufsOpmBDpKnAPnrsjEDGWFds4zTa+9UvE6e/1x09b+xd/8HVHXfw/8dUdF6erXNFAU/E6DWlN3dzgo5cvZXkeq68doKT2Cpm11EcWw8rSGbFe3dlMbhac=,iv:QLfc/PZosmgeP6h8ViF9DJMlfpznLZ2G0Lxz0vkv0l4=,tag:Tv0nwGGG7wzrwVDeWg5T5g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
