apiVersion: v1
data:
    password: ENC[AES256_GCM,data:5DeofWbuB2aXZjxXu+7pVlof9tk=,iv:DBRQR5GoHw/LTONcHks71BM+WWKmH2B0+8x47oHqkj0=,tag:nm7ukbzMxZItIUyrBvsheA==,type:str]
    username: ENC[AES256_GCM,data:0bgQQTYKX3E=,iv:PJXzU8t8xSbXswRuj4xB3+UlWMlujCTOeA3l6IMsjGU=,tag:dLbdJijxUoQmrbKY0rOyYw==,type:str]
kind: Secret
metadata:
    name: bigip-login
    namespace: kube-system
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZWZiNTlaSmUrUjI3eVpS
            VjRqMWkySjNnWmhra1lSYTU1OXpFeldCLzMwCmhVUmFURlJIME56Q0lOR0NqLzZp
            M1dtS1NQUGRVcXdVc3VwQXJpMmxkSTAKLS0tIGk1a2tRSG5QNTdiUnhIZWRUUkxs
            MGhBb0gzTVFuZWlLWlZNQkg0ZWZWUFUKwLsxKMfZcAJqIlcMdwj4codseTU50IFc
            /9rKRBAFy3L77FJGY8o+Qw1+hwDkRRtxZfdTfvpls4wM6ATHGOVSzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ujlph0ptql3ys5ru2pc2kp4247845phntqprfllp4nmhe0wv9gvqjgw30q
    encrypted_regex: ^(data|stringData)$
    mac: ENC[AES256_GCM,data:4tARN8l1lWFrRTWZTurI/g4kmUZEcT6xLHlpPnTkr4+KqSvpjnEl2HODkw6DgdqVXISO1NtLUZ1yklT/q+AqRy5H3WdL13KzQ4m12MXTkMJnWg1hn8yiGmCHtd+/d6qMud8Nyu+4DWYuq+/UfGHQ/C5IhcvR6T+jMiqD0wzDUj4=,iv:kVKzt09h24DgVcjRLkYzrF8rlFjvZma8ZM8acLbS2jc=,tag:n9jwkN4aNvifpo80TKyqQA==,type:str]
    version: 3.13.1
