apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hello-world
  namespace: flux-system
spec:
 # dependsOn:
 #   - name: secrets
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/apps/hello-world
  prune: true
  